name: Deploy to GitHub Pages

on:
  # Executa quando der push na branch main
  push:
    branches: ["main"]
  # Permite rodar manualmente
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: filter to deploy
        run: |
          mkdir temp_deploy
          cp ./index.html temp_deploy/
          cp ./rewards.png temp_deploy/
      # ------------------------------------

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './temp_deploy'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
